version: '3.8'
services:
  ##nest-partners-api:
  ##  env_file:
  ##    - .env
  ##  build:
  ##    context: .
  ##    dockerfile: Dockerfile
  ##  container_name: nest-partners-api
  ##  ports:
  ##    - '3000:3000'
  ##  volumes:
  ##    - .:/app
  ##  environment:
  ##    -  NODE_ENV=${NODE_ENV}
  ##    -  PORT=${PORT}
  ##  depends_on:
  ##    - nest-partners-db
  pg-admin:
    env_file:
      - .env
    image: dpage/pgadmin4
    container_name: pg-admin
    ports:
      - '5050:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - nest-partners-db
    networks:
      - nest-partners-network
    user: root
    volumes:
      - ./pg-admin-data:/var/lib/pgadmin
  nest-partners-db:
    env_file:
      - .env
    image: postgres:13
    container_name: nest-partners-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - nest-partners-network
networks:
  nest-partners-network:
    driver: bridge
